database.url=jdbc:mysql://localhost:3306/your_database_name
database.username=your_usermane
database.password=your_password

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.profiles.default=local