database.url=jdbc:mysql://localhost:3306/your_database_name
database.username=your_usermane
database.password=your_password

spring.datasource.url=jdbc:mysql://localhost:3307/wantsome
spring.datasource.username=root
spring.datasource.password=wantsome

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false